export default Object.freeze({
    SEND_MESSAGE_FROM_USER: 'contacts/SEND_MESSAGE_FROM_USER',
    SEND_MESSAGE_FROM_USER_FULFILLED: 'projects/SEND_MESSAGE_FROM_USER_FULFILLED',
    SEND_MESSAGE_FROM_USER_REJECTED: 'projects/SEND_MESSAGE_FROM_USER_REJECTED'
})