export default Object.freeze({
    SET_CURRENT_USER: 'auth/SET_CURRENT_USER',
    SET_CURRENT_USER_FULFILLED: 'auth/SET_CURRENT_USER_FULFILLED',
    SET_CURRENT_USER_REJECTED: 'auth/SET_CURRENT_USER_REJECTED'
})